//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudBreadAdminWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberItemPurchases
    {
        public string MemberItemPurchaseID { get; set; }
        public string MemberID { get; set; }
        public string ItemListID { get; set; }
        public string PurchaseQuantity { get; set; }
        public string PurchasePrice { get; set; }
        public string PGinfo1 { get; set; }
        public string PGinfo2 { get; set; }
        public string PGinfo3 { get; set; }
        public string PGinfo4 { get; set; }
        public string PGinfo5 { get; set; }
        public string PurchaseDeviceID { get; set; }
        public string PurchaseDeviceIPAddress { get; set; }
        public string PurchaseDeviceMACAddress { get; set; }
        public string PurchaseDT { get; set; }
        public string PurchaseCancelYN { get; set; }
        public string PurchaseCancelDT { get; set; }
        public string PurchaseCancelingStatus { get; set; }
        public string PurchaseCancelReturnedAmount { get; set; }
        public string PurchaseCancelDeviceID { get; set; }
        public string PurchaseCancelDeviceIPAddress { get; set; }
        public string PurchaseCancelDeviceMACAddress { get; set; }
        public string sCol1 { get; set; }
        public string sCol2 { get; set; }
        public string sCol3 { get; set; }
        public string sCol4 { get; set; }
        public string sCol5 { get; set; }
        public string sCol6 { get; set; }
        public string sCol7 { get; set; }
        public string sCol8 { get; set; }
        public string sCol9 { get; set; }
        public string sCol10 { get; set; }
        public string HideYN { get; set; }
        public string DeleteYN { get; set; }
        public string PurchaseCancelConfirmAdminMemberID { get; set; }
        public System.DateTimeOffset CreatedAt { get; set; }
        public System.DateTimeOffset UpdatedAt { get; set; }
        public string DataFromRegion { get; set; }
        public System.DateTimeOffset DataFromRegionDT { get; set; }
    }
}
