//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudBreadAdminWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberAccountBlockLog
    {
        public string MemberAccountBlockID { get; set; }
        public string MemberID { get; set; }
        public string MemberAccountBlockReasonCategory1 { get; set; }
        public string MemberAccountBlockReasonCategory2 { get; set; }
        public string MemberAccountBlockReasonCategory3 { get; set; }
        public string MemberAccountBlockReason { get; set; }
        public string MemberAccountBlockProcess { get; set; }
        public string sCol1 { get; set; }
        public string sCol2 { get; set; }
        public string sCol3 { get; set; }
        public string sCol4 { get; set; }
        public string sCol5 { get; set; }
        public string sCol6 { get; set; }
        public string sCol7 { get; set; }
        public string sCol8 { get; set; }
        public string sCol9 { get; set; }
        public string sCol10 { get; set; }
        public string CreateAdminID { get; set; }
        public string HideYN { get; set; }
        public string DeleteYN { get; set; }
        public System.DateTimeOffset CreatedAt { get; set; }
        public System.DateTimeOffset UpdatedAt { get; set; }
        public string DataFromRegion { get; set; }
        public System.DateTimeOffset DataFromRegionDT { get; set; }
    }
}
