//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudBreadAdminWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Members
    {
        public string MemberID { get; set; }
        public string MemberPWD { get; set; }
        public string EmailAddress { get; set; }
        public string EmailConfirmedYN { get; set; }
        public string PhoneNumber1 { get; set; }
        public string PhoneNumber2 { get; set; }
        public string PINumber { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public string Name3 { get; set; }
        public string DOB { get; set; }
        public string RecommenderID { get; set; }
        public string MemberGroup { get; set; }
        public string LastDeviceID { get; set; }
        public string LastIPaddress { get; set; }
        public string LastLoginDT { get; set; }
        public string LastLogoutDT { get; set; }
        public string LastMACAddress { get; set; }
        public string AccountBlockYN { get; set; }
        public string AccountBlockEndDT { get; set; }
        public string AnonymousYN { get; set; }
        public string C3rdAuthProvider { get; set; }
        public string C3rdAuthID { get; set; }
        public string C3rdAuthParam { get; set; }
        public string PushNotificationID { get; set; }
        public string PushNotificationProvider { get; set; }
        public string PushNotificationGroup { get; set; }
        public string sCol1 { get; set; }
        public string sCol2 { get; set; }
        public string sCol3 { get; set; }
        public string sCol4 { get; set; }
        public string sCol5 { get; set; }
        public string sCol6 { get; set; }
        public string sCol7 { get; set; }
        public string sCol8 { get; set; }
        public string sCol9 { get; set; }
        public string sCol10 { get; set; }
        public string TimeZoneID { get; set; }
        public string HideYN { get; set; }
        public string DeleteYN { get; set; }
        public System.DateTimeOffset CreatedAt { get; set; }
        public System.DateTimeOffset UpdatedAt { get; set; }
        public string DataFromRegion { get; set; }
        public System.DateTimeOffset DataFromRegionDT { get; set; }
    }
}
